# Put the following lines in your ~/.config/kitty/kitty.conf
foreground #f1e9d2
background #252623
color0 #111210
color1 #e75a7c
color2 #8fb573
color3 #dbb651
color4 #57a5e5
color5 #aaaaff
color6 #70c2be
color7 #f1e9d2
color8 #5b5e5a
color9 #e75a7c
color10 #8fb573
color11 #dbb651
color12 #57a5e5
color13 #aaaaff
color14 #70c2be
color15 #f1e9d2
cursor #f1e9d2
cursor_text_color #252623
selection_foreground none
selection_background #3a3d37
tab_bar_background #141413
active_tab_foreground #f1e9d2
active_tab_background #252623
inactive_tab_foreground #838781
inactive_tab_background #1b1c1a
active_border_color #252623
inactive_border_color #3a3d37
