foreground #a7a7a7
background #121212
cursor #a7a7a7
cursor_text_color #121212
selection_foreground none
selection_background #323232
tab_bar_background #090909
active_tab_foreground #a7a7a7
active_tab_background #121212
inactive_tab_foreground #737373
inactive_tab_background #0d0d0d
active_border_color #d5d5d5
inactive_border_color #323232

color0 #121212
color8 #121212

#: red
color1                          #e67e80
color9                          #e67e80

#: green
color2                          #a7c080
color10                         #a7c080

#: yellow
color3                          #dbbc7f
color11                         #dbbc7f

#: blue
color4                          #7fbbb3
color12                         #7fbbb3

#: magenta
color5                          #d699b6
color13                         #d699b6

#: cyan
color6                          #83c092
color14                         #83c092

color7  #a7a7a7	
color15 #a7a7a7


