# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Hyprlock                                                          
# Original config submitted by https://github.com/SherLock707

general {
    grace = 1
}

background {
    monitor =
	#path = screenshot   # screenshot of your desktop
	path = $HOME/wallpapers/forest.jpg
    #color = $color7
}


