foreground #a7a7a7
background #121212
cursor #a7a7a7
cursor_text_color #121212
selection_foreground none
selection_background #323232
tab_bar_background #090909
active_tab_foreground #a7a7a7
active_tab_background #121212
inactive_tab_foreground #737373
inactive_tab_background #0d0d0d
active_border_color #d5d5d5
inactive_border_color #323232

color0 #121212
color8 #121212

#: red
color1                          #c25757
color9                          #c25757

#: green
color2                          #a7c8a7
color10                         #a7c8a7

#: yellow
color3                          #c8c8a7
color11                         #c8c8a7

#: blue
color4                          #c8c8ff
color12                         #c8c8ff

#: magenta
color5                          #c8a7c8
color13                         #c8a7c8

#: cyan
color6                          #a7c8c8
color14                         #a7c8c8

color7  #a7a7a7	
color15 #a7a7a7


